import type { Metadata } from "next";
import { Geist } from "next/font/google"; // Asumsi font Geist sudah terinstall
import "./globals.css";
import { Navbar } from "@/src/components/navbar";
import { Footer } from "@/src/components/footer";
import { Toaster } from "sonner"; // Toast notification

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Selamat Datang Di YPMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id" suppressHydrationWarning>
      <body
        className={`${geistSans.className} flex min-h-screen flex-col antialiased`}
      >
        {/* Navbar di atas */}
        <Navbar />

        {/* Konten Utama (akan memanjang mengisi ruang kosong) */}
        <main className="flex-1">{children}</main>

        {/* Footer di bawah */}
        <Footer />

        {/* Komponen Utility */}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
